/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.accountsmgmt.v1.ReservedResource;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ClusterAuthorizationRequest
 */


public class ClusterAuthorizationRequest {
  @JsonProperty("byoc")
  private Boolean byoc = null;

  @JsonProperty("account_username")
  private String accountUsername = null;

  @JsonProperty("availability_zone")
  private String availabilityZone = null;

  @JsonProperty("cluster_id")
  private String clusterId = null;

  @JsonProperty("disconnected")
  private Boolean disconnected = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("external_cluster_id")
  private String externalClusterId = null;

  @JsonProperty("managed")
  private Boolean managed = null;

  @JsonProperty("reserve")
  private Boolean reserve = null;

  @JsonProperty("resources")
  private List<ReservedResource> resources = null;

  public ClusterAuthorizationRequest byoc(Boolean byoc) {
    this.byoc = byoc;
    return this;
  }

   /**
   * Get byoc
   * @return byoc
  **/
  @Schema(description = "")
  public Boolean isByoc() {
    return byoc;
  }

  public void setByoc(Boolean byoc) {
    this.byoc = byoc;
  }

  public ClusterAuthorizationRequest accountUsername(String accountUsername) {
    this.accountUsername = accountUsername;
    return this;
  }

   /**
   * Get accountUsername
   * @return accountUsername
  **/
  @Schema(description = "")
  public String getAccountUsername() {
    return accountUsername;
  }

  public void setAccountUsername(String accountUsername) {
    this.accountUsername = accountUsername;
  }

  public ClusterAuthorizationRequest availabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
    return this;
  }

   /**
   * Get availabilityZone
   * @return availabilityZone
  **/
  @Schema(description = "")
  public String getAvailabilityZone() {
    return availabilityZone;
  }

  public void setAvailabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
  }

  public ClusterAuthorizationRequest clusterId(String clusterId) {
    this.clusterId = clusterId;
    return this;
  }

   /**
   * Get clusterId
   * @return clusterId
  **/
  @Schema(description = "")
  public String getClusterId() {
    return clusterId;
  }

  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }

  public ClusterAuthorizationRequest disconnected(Boolean disconnected) {
    this.disconnected = disconnected;
    return this;
  }

   /**
   * Get disconnected
   * @return disconnected
  **/
  @Schema(description = "")
  public Boolean isDisconnected() {
    return disconnected;
  }

  public void setDisconnected(Boolean disconnected) {
    this.disconnected = disconnected;
  }

  public ClusterAuthorizationRequest displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ClusterAuthorizationRequest externalClusterId(String externalClusterId) {
    this.externalClusterId = externalClusterId;
    return this;
  }

   /**
   * Get externalClusterId
   * @return externalClusterId
  **/
  @Schema(description = "")
  public String getExternalClusterId() {
    return externalClusterId;
  }

  public void setExternalClusterId(String externalClusterId) {
    this.externalClusterId = externalClusterId;
  }

  public ClusterAuthorizationRequest managed(Boolean managed) {
    this.managed = managed;
    return this;
  }

   /**
   * Get managed
   * @return managed
  **/
  @Schema(description = "")
  public Boolean isManaged() {
    return managed;
  }

  public void setManaged(Boolean managed) {
    this.managed = managed;
  }

  public ClusterAuthorizationRequest reserve(Boolean reserve) {
    this.reserve = reserve;
    return this;
  }

   /**
   * Get reserve
   * @return reserve
  **/
  @Schema(description = "")
  public Boolean isReserve() {
    return reserve;
  }

  public void setReserve(Boolean reserve) {
    this.reserve = reserve;
  }

  public ClusterAuthorizationRequest resources(List<ReservedResource> resources) {
    this.resources = resources;
    return this;
  }

  public ClusterAuthorizationRequest addResourcesItem(ReservedResource resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @Schema(description = "")
  public List<ReservedResource> getResources() {
    return resources;
  }

  public void setResources(List<ReservedResource> resources) {
    this.resources = resources;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterAuthorizationRequest clusterAuthorizationRequest = (ClusterAuthorizationRequest) o;
    return Objects.equals(this.byoc, clusterAuthorizationRequest.byoc) &&
        Objects.equals(this.accountUsername, clusterAuthorizationRequest.accountUsername) &&
        Objects.equals(this.availabilityZone, clusterAuthorizationRequest.availabilityZone) &&
        Objects.equals(this.clusterId, clusterAuthorizationRequest.clusterId) &&
        Objects.equals(this.disconnected, clusterAuthorizationRequest.disconnected) &&
        Objects.equals(this.displayName, clusterAuthorizationRequest.displayName) &&
        Objects.equals(this.externalClusterId, clusterAuthorizationRequest.externalClusterId) &&
        Objects.equals(this.managed, clusterAuthorizationRequest.managed) &&
        Objects.equals(this.reserve, clusterAuthorizationRequest.reserve) &&
        Objects.equals(this.resources, clusterAuthorizationRequest.resources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byoc, accountUsername, availabilityZone, clusterId, disconnected, displayName, externalClusterId, managed, reserve, resources);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterAuthorizationRequest {\n");
    
    sb.append("    byoc: ").append(toIndentedString(byoc)).append("\n");
    sb.append("    accountUsername: ").append(toIndentedString(accountUsername)).append("\n");
    sb.append("    availabilityZone: ").append(toIndentedString(availabilityZone)).append("\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    disconnected: ").append(toIndentedString(disconnected)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    externalClusterId: ").append(toIndentedString(externalClusterId)).append("\n");
    sb.append("    managed: ").append(toIndentedString(managed)).append("\n");
    sb.append("    reserve: ").append(toIndentedString(reserve)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
