/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.accountsmgmt.v1.ReservedResource;
import io.fabric8.ocm.model.accountsmgmt.v1.Subscription;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ClusterAuthorizationResponse
 */


public class ClusterAuthorizationResponse {
  @JsonProperty("allowed")
  private Boolean allowed = null;

  @JsonProperty("excess_resources")
  private List<ReservedResource> excessResources = null;

  @JsonProperty("subscription")
  private Subscription subscription = null;

  public ClusterAuthorizationResponse allowed(Boolean allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Get allowed
   * @return allowed
  **/
  @Schema(description = "")
  public Boolean isAllowed() {
    return allowed;
  }

  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }

  public ClusterAuthorizationResponse excessResources(List<ReservedResource> excessResources) {
    this.excessResources = excessResources;
    return this;
  }

  public ClusterAuthorizationResponse addExcessResourcesItem(ReservedResource excessResourcesItem) {
    if (this.excessResources == null) {
      this.excessResources = new ArrayList<>();
    }
    this.excessResources.add(excessResourcesItem);
    return this;
  }

   /**
   * Get excessResources
   * @return excessResources
  **/
  @Schema(description = "")
  public List<ReservedResource> getExcessResources() {
    return excessResources;
  }

  public void setExcessResources(List<ReservedResource> excessResources) {
    this.excessResources = excessResources;
  }

  public ClusterAuthorizationResponse subscription(Subscription subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @Schema(description = "")
  public Subscription getSubscription() {
    return subscription;
  }

  public void setSubscription(Subscription subscription) {
    this.subscription = subscription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterAuthorizationResponse clusterAuthorizationResponse = (ClusterAuthorizationResponse) o;
    return Objects.equals(this.allowed, clusterAuthorizationResponse.allowed) &&
        Objects.equals(this.excessResources, clusterAuthorizationResponse.excessResources) &&
        Objects.equals(this.subscription, clusterAuthorizationResponse.subscription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowed, excessResources, subscription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterAuthorizationResponse {\n");
    
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    excessResources: ").append(toIndentedString(excessResources)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
