/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PullSecretsRequest
 */


public class PullSecretsRequest {
  @JsonProperty("external_resource_id")
  private String externalResourceId = null;

  public PullSecretsRequest externalResourceId(String externalResourceId) {
    this.externalResourceId = externalResourceId;
    return this;
  }

   /**
   * Get externalResourceId
   * @return externalResourceId
  **/
  @Schema(description = "")
  public String getExternalResourceId() {
    return externalResourceId;
  }

  public void setExternalResourceId(String externalResourceId) {
    this.externalResourceId = externalResourceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullSecretsRequest pullSecretsRequest = (PullSecretsRequest) o;
    return Objects.equals(this.externalResourceId, pullSecretsRequest.externalResourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalResourceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullSecretsRequest {\n");
    
    sb.append("    externalResourceId: ").append(toIndentedString(externalResourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
