/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Identifies computing resources 
 */
@Schema(description = "Identifies computing resources ")

public class Resource {
  @JsonProperty("kind")
  private String kind = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("byoc")
  private Boolean byoc = null;

  @JsonProperty("sku")
  private String sku = null;

  @JsonProperty("allowed")
  private Integer allowed = null;

  @JsonProperty("availability_zone_type")
  private String availabilityZoneType = null;

  @JsonProperty("resource_name")
  private String resourceName = null;

  @JsonProperty("resource_type")
  private String resourceType = null;

  public Resource kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Indicates the type of this object. Will be &#x27;Resource&#x27; if this is a complete object or &#x27;ResourceLink&#x27; if it is just a link. 
   * @return kind
  **/
  @Schema(description = "Indicates the type of this object. Will be 'Resource' if this is a complete object or 'ResourceLink' if it is just a link. ")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public Resource id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the object. 
   * @return id
  **/
  @Schema(description = "Unique identifier of the object. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Resource href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Self link. 
   * @return href
  **/
  @Schema(description = "Self link. ")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public Resource byoc(Boolean byoc) {
    this.byoc = byoc;
    return this;
  }

   /**
   * Get byoc
   * @return byoc
  **/
  @Schema(description = "")
  public Boolean isByoc() {
    return byoc;
  }

  public void setByoc(Boolean byoc) {
    this.byoc = byoc;
  }

  public Resource sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @Schema(description = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public Resource allowed(Integer allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Number of allowed nodes 
   * @return allowed
  **/
  @Schema(description = "Number of allowed nodes ")
  public Integer getAllowed() {
    return allowed;
  }

  public void setAllowed(Integer allowed) {
    this.allowed = allowed;
  }

  public Resource availabilityZoneType(String availabilityZoneType) {
    this.availabilityZoneType = availabilityZoneType;
    return this;
  }

   /**
   * Get availabilityZoneType
   * @return availabilityZoneType
  **/
  @Schema(description = "")
  public String getAvailabilityZoneType() {
    return availabilityZoneType;
  }

  public void setAvailabilityZoneType(String availabilityZoneType) {
    this.availabilityZoneType = availabilityZoneType;
  }

  public Resource resourceName(String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

   /**
   * platform-specific name, such as \&quot;M5.2Xlarge\&quot; for a type of EC2 node 
   * @return resourceName
  **/
  @Schema(description = "platform-specific name, such as \"M5.2Xlarge\" for a type of EC2 node ")
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }

  public Resource resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @Schema(description = "")
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.kind, resource.kind) &&
        Objects.equals(this.id, resource.id) &&
        Objects.equals(this.href, resource.href) &&
        Objects.equals(this.byoc, resource.byoc) &&
        Objects.equals(this.sku, resource.sku) &&
        Objects.equals(this.allowed, resource.allowed) &&
        Objects.equals(this.availabilityZoneType, resource.availabilityZoneType) &&
        Objects.equals(this.resourceName, resource.resourceName) &&
        Objects.equals(this.resourceType, resource.resourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, id, href, byoc, sku, allowed, availabilityZoneType, resourceName, resourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    byoc: ").append(toIndentedString(byoc)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    availabilityZoneType: ").append(toIndentedString(availabilityZoneType)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
