/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
/**
 * ResourceQuota
 */


public class ResourceQuota {
  @JsonProperty("kind")
  private String kind = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("byoc")
  private Boolean byoc = null;

  @JsonProperty("sku")
  private String sku = null;

  @JsonProperty("allowed")
  private Integer allowed = null;

  @JsonProperty("availability_zone_type")
  private String availabilityZoneType = null;

  @JsonProperty("created_at")
  private LocalDateTime createdAt = null;

  @JsonProperty("organization_id")
  private String organizationId = null;

  @JsonProperty("resource_name")
  private String resourceName = null;

  @JsonProperty("resource_type")
  private String resourceType = null;

  @JsonProperty("sku_count")
  private Integer skuCount = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("updated_at")
  private LocalDateTime updatedAt = null;

  public ResourceQuota kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Indicates the type of this object. Will be &#x27;ResourceQuota&#x27; if this is a complete object or &#x27;ResourceQuotaLink&#x27; if it is just a link. 
   * @return kind
  **/
  @Schema(description = "Indicates the type of this object. Will be 'ResourceQuota' if this is a complete object or 'ResourceQuotaLink' if it is just a link. ")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ResourceQuota id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the object. 
   * @return id
  **/
  @Schema(description = "Unique identifier of the object. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResourceQuota href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Self link. 
   * @return href
  **/
  @Schema(description = "Self link. ")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public ResourceQuota byoc(Boolean byoc) {
    this.byoc = byoc;
    return this;
  }

   /**
   * Get byoc
   * @return byoc
  **/
  @Schema(description = "")
  public Boolean isByoc() {
    return byoc;
  }

  public void setByoc(Boolean byoc) {
    this.byoc = byoc;
  }

  public ResourceQuota sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @Schema(description = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public ResourceQuota allowed(Integer allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Get allowed
   * @return allowed
  **/
  @Schema(description = "")
  public Integer getAllowed() {
    return allowed;
  }

  public void setAllowed(Integer allowed) {
    this.allowed = allowed;
  }

  public ResourceQuota availabilityZoneType(String availabilityZoneType) {
    this.availabilityZoneType = availabilityZoneType;
    return this;
  }

   /**
   * Get availabilityZoneType
   * @return availabilityZoneType
  **/
  @Schema(description = "")
  public String getAvailabilityZoneType() {
    return availabilityZoneType;
  }

  public void setAvailabilityZoneType(String availabilityZoneType) {
    this.availabilityZoneType = availabilityZoneType;
  }

  public ResourceQuota createdAt(LocalDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public LocalDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(LocalDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ResourceQuota organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @Schema(description = "")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public ResourceQuota resourceName(String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

   /**
   * Get resourceName
   * @return resourceName
  **/
  @Schema(description = "")
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }

  public ResourceQuota resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @Schema(description = "")
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  public ResourceQuota skuCount(Integer skuCount) {
    this.skuCount = skuCount;
    return this;
  }

   /**
   * Get skuCount
   * @return skuCount
  **/
  @Schema(description = "")
  public Integer getSkuCount() {
    return skuCount;
  }

  public void setSkuCount(Integer skuCount) {
    this.skuCount = skuCount;
  }

  public ResourceQuota type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ResourceQuota updatedAt(LocalDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public LocalDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(LocalDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceQuota resourceQuota = (ResourceQuota) o;
    return Objects.equals(this.kind, resourceQuota.kind) &&
        Objects.equals(this.id, resourceQuota.id) &&
        Objects.equals(this.href, resourceQuota.href) &&
        Objects.equals(this.byoc, resourceQuota.byoc) &&
        Objects.equals(this.sku, resourceQuota.sku) &&
        Objects.equals(this.allowed, resourceQuota.allowed) &&
        Objects.equals(this.availabilityZoneType, resourceQuota.availabilityZoneType) &&
        Objects.equals(this.createdAt, resourceQuota.createdAt) &&
        Objects.equals(this.organizationId, resourceQuota.organizationId) &&
        Objects.equals(this.resourceName, resourceQuota.resourceName) &&
        Objects.equals(this.resourceType, resourceQuota.resourceType) &&
        Objects.equals(this.skuCount, resourceQuota.skuCount) &&
        Objects.equals(this.type, resourceQuota.type) &&
        Objects.equals(this.updatedAt, resourceQuota.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, id, href, byoc, sku, allowed, availabilityZoneType, createdAt, organizationId, resourceName, resourceType, skuCount, type, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceQuota {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    byoc: ").append(toIndentedString(byoc)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    availabilityZoneType: ").append(toIndentedString(availabilityZoneType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    skuCount: ").append(toIndentedString(skuCount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
