/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Identifies sku rule 
 */
@Schema(description = "Identifies sku rule ")

public class SkuRule {
  @JsonProperty("kind")
  private String kind = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("allowed")
  private Integer allowed = null;

  @JsonProperty("quota_id")
  private String quotaId = null;

  @JsonProperty("sku")
  private String sku = null;

  public SkuRule kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Indicates the type of this object. Will be &#x27;SkuRule&#x27; if this is a complete object or &#x27;SkuRuleLink&#x27; if it is just a link. 
   * @return kind
  **/
  @Schema(description = "Indicates the type of this object. Will be 'SkuRule' if this is a complete object or 'SkuRuleLink' if it is just a link. ")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public SkuRule id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the object. 
   * @return id
  **/
  @Schema(description = "Unique identifier of the object. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SkuRule href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Self link. 
   * @return href
  **/
  @Schema(description = "Self link. ")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public SkuRule allowed(Integer allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Specifies the allowed parameter for calculation 
   * @return allowed
  **/
  @Schema(description = "Specifies the allowed parameter for calculation ")
  public Integer getAllowed() {
    return allowed;
  }

  public void setAllowed(Integer allowed) {
    this.allowed = allowed;
  }

  public SkuRule quotaId(String quotaId) {
    this.quotaId = quotaId;
    return this;
  }

   /**
   * Specifies the quota id 
   * @return quotaId
  **/
  @Schema(description = "Specifies the quota id ")
  public String getQuotaId() {
    return quotaId;
  }

  public void setQuotaId(String quotaId) {
    this.quotaId = quotaId;
  }

  public SkuRule sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Specifies the sku, such as \&quot;\&quot;MW00504\&quot;\&quot; 
   * @return sku
  **/
  @Schema(description = "Specifies the sku, such as \"\"MW00504\"\" ")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkuRule skuRule = (SkuRule) o;
    return Objects.equals(this.kind, skuRule.kind) &&
        Objects.equals(this.id, skuRule.id) &&
        Objects.equals(this.href, skuRule.href) &&
        Objects.equals(this.allowed, skuRule.allowed) &&
        Objects.equals(this.quotaId, skuRule.quotaId) &&
        Objects.equals(this.sku, skuRule.sku);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, id, href, allowed, quotaId, sku);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkuRule {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    quotaId: ").append(toIndentedString(quotaId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
