/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.accountsmgmt.v1.PlanID;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Registration of a new subscription. 
 */
@Schema(description = "Registration of a new subscription. ")

public class SubscriptionRegistration {
  @JsonProperty("cluster_uuid")
  private String clusterUuid = null;

  @JsonProperty("console_url")
  private String consoleUrl = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("plan_id")
  private PlanID planId = null;

  @JsonProperty("status")
  private String status = null;

  public SubscriptionRegistration clusterUuid(String clusterUuid) {
    this.clusterUuid = clusterUuid;
    return this;
  }

   /**
   * External cluster ID. 
   * @return clusterUuid
  **/
  @Schema(description = "External cluster ID. ")
  public String getClusterUuid() {
    return clusterUuid;
  }

  public void setClusterUuid(String clusterUuid) {
    this.clusterUuid = clusterUuid;
  }

  public SubscriptionRegistration consoleUrl(String consoleUrl) {
    this.consoleUrl = consoleUrl;
    return this;
  }

   /**
   * Console URL of subscription (optional). 
   * @return consoleUrl
  **/
  @Schema(description = "Console URL of subscription (optional). ")
  public String getConsoleUrl() {
    return consoleUrl;
  }

  public void setConsoleUrl(String consoleUrl) {
    this.consoleUrl = consoleUrl;
  }

  public SubscriptionRegistration displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Display name of subscription (optional). 
   * @return displayName
  **/
  @Schema(description = "Display name of subscription (optional). ")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public SubscriptionRegistration planId(PlanID planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @Schema(description = "")
  public PlanID getPlanId() {
    return planId;
  }

  public void setPlanId(PlanID planId) {
    this.planId = planId;
  }

  public SubscriptionRegistration status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of subscription. 
   * @return status
  **/
  @Schema(description = "Status of subscription. ")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionRegistration subscriptionRegistration = (SubscriptionRegistration) o;
    return Objects.equals(this.clusterUuid, subscriptionRegistration.clusterUuid) &&
        Objects.equals(this.consoleUrl, subscriptionRegistration.consoleUrl) &&
        Objects.equals(this.displayName, subscriptionRegistration.displayName) &&
        Objects.equals(this.planId, subscriptionRegistration.planId) &&
        Objects.equals(this.status, subscriptionRegistration.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterUuid, consoleUrl, displayName, planId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionRegistration {\n");
    
    sb.append("    clusterUuid: ").append(toIndentedString(clusterUuid)).append("\n");
    sb.append("    consoleUrl: ").append(toIndentedString(consoleUrl)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
