/*
 * accounts_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.accountsmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * A template parameter is used in an email to replace placeholder content with values specific to the email recipient. 
 */
@Schema(description = "A template parameter is used in an email to replace placeholder content with values specific to the email recipient. ")

public class TemplateParameter {
  @JsonProperty("content")
  private String content = null;

  @JsonProperty("name")
  private String name = null;

  public TemplateParameter content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The content that will replace the template parameter in the email 
   * @return content
  **/
  @Schema(description = "The content that will replace the template parameter in the email ")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TemplateParameter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the value to be replaced 
   * @return name
  **/
  @Schema(description = "Name of the value to be replaced ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateParameter templateParameter = (TemplateParameter) o;
    return Objects.equals(this.content, templateParameter.content) &&
        Objects.equals(this.name, templateParameter.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateParameter {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
