/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.clustersmgmt.v1.CloudProvider;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Description of a region of a cloud provider. 
 */
@Schema(description = "Description of a region of a cloud provider. ")

public class CloudRegion {
  @JsonProperty("kind")
  private String kind = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("cloud_provider")
  private CloudProvider cloudProvider = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("supports_multi_az")
  private Boolean supportsMultiAz = null;

  public CloudRegion kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Indicates the type of this object. Will be &#x27;CloudRegion&#x27; if this is a complete object or &#x27;CloudRegionLink&#x27; if it is just a link. 
   * @return kind
  **/
  @Schema(description = "Indicates the type of this object. Will be 'CloudRegion' if this is a complete object or 'CloudRegionLink' if it is just a link. ")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public CloudRegion id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the object. 
   * @return id
  **/
  @Schema(description = "Unique identifier of the object. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CloudRegion href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Self link. 
   * @return href
  **/
  @Schema(description = "Self link. ")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public CloudRegion cloudProvider(CloudProvider cloudProvider) {
    this.cloudProvider = cloudProvider;
    return this;
  }

   /**
   * Get cloudProvider
   * @return cloudProvider
  **/
  @Schema(description = "")
  public CloudProvider getCloudProvider() {
    return cloudProvider;
  }

  public void setCloudProvider(CloudProvider cloudProvider) {
    this.cloudProvider = cloudProvider;
  }

  public CloudRegion displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Name of the region for display purposes, for example &#x60;N. Virginia&#x60;. 
   * @return displayName
  **/
  @Schema(description = "Name of the region for display purposes, for example `N. Virginia`. ")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public CloudRegion enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether the region is enabled for deploying an OSD cluster. 
   * @return enabled
  **/
  @Schema(description = "Whether the region is enabled for deploying an OSD cluster. ")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public CloudRegion name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Human friendly identifier of the region, for example &#x60;us-east-1&#x60;.  NOTE: Currently for all cloud providers and all regions &#x60;id&#x60; and &#x60;name&#x60; have exactly the same values. 
   * @return name
  **/
  @Schema(description = "Human friendly identifier of the region, for example `us-east-1`.  NOTE: Currently for all cloud providers and all regions `id` and `name` have exactly the same values. ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CloudRegion supportsMultiAz(Boolean supportsMultiAz) {
    this.supportsMultiAz = supportsMultiAz;
    return this;
  }

   /**
   * Whether the region supports multiple availability zones. 
   * @return supportsMultiAz
  **/
  @Schema(description = "Whether the region supports multiple availability zones. ")
  public Boolean isSupportsMultiAz() {
    return supportsMultiAz;
  }

  public void setSupportsMultiAz(Boolean supportsMultiAz) {
    this.supportsMultiAz = supportsMultiAz;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudRegion cloudRegion = (CloudRegion) o;
    return Objects.equals(this.kind, cloudRegion.kind) &&
        Objects.equals(this.id, cloudRegion.id) &&
        Objects.equals(this.href, cloudRegion.href) &&
        Objects.equals(this.cloudProvider, cloudRegion.cloudProvider) &&
        Objects.equals(this.displayName, cloudRegion.displayName) &&
        Objects.equals(this.enabled, cloudRegion.enabled) &&
        Objects.equals(this.name, cloudRegion.name) &&
        Objects.equals(this.supportsMultiAz, cloudRegion.supportsMultiAz);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, id, href, cloudProvider, displayName, enabled, name, supportsMultiAz);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudRegion {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    cloudProvider: ").append(toIndentedString(cloudProvider)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportsMultiAz: ").append(toIndentedString(supportsMultiAz)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
