/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Registration of a new cluster to the service. 
 */
@Schema(description = "Registration of a new cluster to the service. ")

public class ClusterRegistration {
  @JsonProperty("external_id")
  private String externalId = null;

  @JsonProperty("organization_id")
  private String organizationId = null;

  @JsonProperty("subscription_id")
  private String subscriptionId = null;

  public ClusterRegistration externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Identifier of the cluster generated by the installer.  For example, to register a cluster that has been provisioned outside of this service, send a a request like this:   &#x60;&#x60;&#x60; POST /api/clusters_mgmt/v1/register_cluster HTTP/1.1 &#x60;&#x60;&#x60;  With a request body like this:   &#x60;&#x60;&#x60; {   \&quot;external_id\&quot;: \&quot;d656aecf-11a6-4782-ad86-8f72638449ba\&quot; } &#x60;&#x60;&#x60; 
   * @return externalId
  **/
  @Schema(description = "Identifier of the cluster generated by the installer.  For example, to register a cluster that has been provisioned outside of this service, send a a request like this:   ``` POST /api/clusters_mgmt/v1/register_cluster HTTP/1.1 ```  With a request body like this:   ``` {   \"external_id\": \"d656aecf-11a6-4782-ad86-8f72638449ba\" } ``` ")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ClusterRegistration organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Optional Organization identifier of the cluster generated by the account manager. 
   * @return organizationId
  **/
  @Schema(description = "Optional Organization identifier of the cluster generated by the account manager. ")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public ClusterRegistration subscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

   /**
   * Subscription identifier of the cluster generated by the account manager. 
   * @return subscriptionId
  **/
  @Schema(description = "Subscription identifier of the cluster generated by the account manager. ")
  public String getSubscriptionId() {
    return subscriptionId;
  }

  public void setSubscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterRegistration clusterRegistration = (ClusterRegistration) o;
    return Objects.equals(this.externalId, clusterRegistration.externalId) &&
        Objects.equals(this.organizationId, clusterRegistration.organizationId) &&
        Objects.equals(this.subscriptionId, clusterRegistration.subscriptionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, organizationId, subscriptionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterRegistration {\n");
    
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
