/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.clustersmgmt.v1.ListeningMethod;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Information about the API of a cluster. 
 */
@Schema(description = "Information about the API of a cluster. ")

public class ClusterAPI {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("listening")
  private ListeningMethod listening = null;

  public ClusterAPI url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL of the API server of the cluster. 
   * @return url
  **/
  @Schema(description = "The URL of the API server of the cluster. ")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ClusterAPI listening(ListeningMethod listening) {
    this.listening = listening;
    return this;
  }

   /**
   * Get listening
   * @return listening
  **/
  @Schema(description = "")
  public ListeningMethod getListening() {
    return listening;
  }

  public void setListening(ListeningMethod listening) {
    this.listening = listening;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterAPI clusterAPI = (ClusterAPI) o;
    return Objects.equals(this.url, clusterAPI.url) &&
        Objects.equals(this.listening, clusterAPI.listening);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, listening);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterAPI {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    listening: ").append(toIndentedString(listening)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
