/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.clustersmgmt.v1.ClusterOperatorInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Provides detailed information about the operators installed on the cluster. 
 */
@Schema(description = "Provides detailed information about the operators installed on the cluster. ")

public class ClusterOperatorsInfo {
  @JsonProperty("operators")
  private List<ClusterOperatorInfo> operators = null;

  public ClusterOperatorsInfo operators(List<ClusterOperatorInfo> operators) {
    this.operators = operators;
    return this;
  }

  public ClusterOperatorsInfo addOperatorsItem(ClusterOperatorInfo operatorsItem) {
    if (this.operators == null) {
      this.operators = new ArrayList<>();
    }
    this.operators.add(operatorsItem);
    return this;
  }

   /**
   * Get operators
   * @return operators
  **/
  @Schema(description = "")
  public List<ClusterOperatorInfo> getOperators() {
    return operators;
  }

  public void setOperators(List<ClusterOperatorInfo> operators) {
    this.operators = operators;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterOperatorsInfo clusterOperatorsInfo = (ClusterOperatorsInfo) o;
    return Objects.equals(this.operators, clusterOperatorsInfo.operators);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operators);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterOperatorsInfo {\n");
    
    sb.append("    operators: ").append(toIndentedString(operators)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
