/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.fabric8.ocm.model.clustersmgmt.v1.CPUTotalNodeRoleOSMetricNode;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Representation of information from telemetry about the CPU capacity by node role and OS of a cluster. 
 */
@Schema(description = "Representation of information from telemetry about the CPU capacity by node role and OS of a cluster. ")

public class CPUTotalsNodeRoleOSMetricNode {
  @JsonProperty("cpu_totals")
  private List<CPUTotalNodeRoleOSMetricNode> cpuTotals = null;

  public CPUTotalsNodeRoleOSMetricNode cpuTotals(List<CPUTotalNodeRoleOSMetricNode> cpuTotals) {
    this.cpuTotals = cpuTotals;
    return this;
  }

  public CPUTotalsNodeRoleOSMetricNode addCpuTotalsItem(CPUTotalNodeRoleOSMetricNode cpuTotalsItem) {
    if (this.cpuTotals == null) {
      this.cpuTotals = new ArrayList<>();
    }
    this.cpuTotals.add(cpuTotalsItem);
    return this;
  }

   /**
   * Get cpuTotals
   * @return cpuTotals
  **/
  @Schema(description = "")
  public List<CPUTotalNodeRoleOSMetricNode> getCpuTotals() {
    return cpuTotals;
  }

  public void setCpuTotals(List<CPUTotalNodeRoleOSMetricNode> cpuTotals) {
    this.cpuTotals = cpuTotals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CPUTotalsNodeRoleOSMetricNode cpUTotalsNodeRoleOSMetricNode = (CPUTotalsNodeRoleOSMetricNode) o;
    return Objects.equals(this.cpuTotals, cpUTotalsNodeRoleOSMetricNode.cpuTotals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpuTotals);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CPUTotalsNodeRoleOSMetricNode {\n");
    
    sb.append("    cpuTotals: ").append(toIndentedString(cpuTotals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
