/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Counts of different classes of nodes inside a flavour. 
 */
@Schema(description = "Counts of different classes of nodes inside a flavour. ")

public class FlavourNodes {
  @JsonProperty("master")
  private Integer master = null;

  public FlavourNodes master(Integer master) {
    this.master = master;
    return this;
  }

   /**
   * Number of master nodes of the cluster. 
   * @return master
  **/
  @Schema(description = "Number of master nodes of the cluster. ")
  public Integer getMaster() {
    return master;
  }

  public void setMaster(Integer master) {
    this.master = master;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlavourNodes flavourNodes = (FlavourNodes) o;
    return Objects.equals(this.master, flavourNodes.master);
  }

  @Override
  public int hashCode() {
    return Objects.hash(master);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlavourNodes {\n");
    
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
