/*
 * clusters_mgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.fabric8.ocm.model.clustersmgmt.v1;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Details for &#x60;htpasswd&#x60; identity providers. 
 */
@Schema(description = "Details for `htpasswd` identity providers. ")

public class HTPasswdIdentityProvider {
  @JsonProperty("password")
  private String password = null;

  @JsonProperty("username")
  private String username = null;

  public HTPasswdIdentityProvider password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password to be used in the _HTPasswd_ data file. 
   * @return password
  **/
  @Schema(description = "Password to be used in the _HTPasswd_ data file. ")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public HTPasswdIdentityProvider username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username to be used in the _HTPasswd_ data file. 
   * @return username
  **/
  @Schema(description = "Username to be used in the _HTPasswd_ data file. ")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTPasswdIdentityProvider htPasswdIdentityProvider = (HTPasswdIdentityProvider) o;
    return Objects.equals(this.password, htPasswdIdentityProvider.password) &&
        Objects.equals(this.username, htPasswdIdentityProvider.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTPasswdIdentityProvider {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
